#!/bin/sh
APPDIR=`dirname $0`;
$JAVA_HOME/bin/java -XstartOnFirstThread -Dgwt.args="-out www-test" -Xmx256M -cp "$APPDIR/src:$APPDIR/test:$APPDIR/bin:$APPDIR/lib/junit-3.8.2.jar:/Users/dkappe/java-packs/gwt-mac-1.5.2/gwt-user.jar:/Users/dkappe/java-packs/gwt-mac-1.5.2/gwt-dev-mac.jar" junit.textui.TestRunner com.pathf.gwt.util.json.client.JSONWrapperTest "$@";
